lib:
	vlib work

## Aligner IP 
rtl = ../DUT/cfs_synch.sv\
      ../DUT/cfs_synch_fifo.sv\
      ../DUT/cfs_rx_ctrl.sv\
      ../DUT/cfs_ctrl.sv\
      ../DUT/cfs_tx_ctrl.sv\
      ../DUT/cfs_edge_detect.sv\
      ../DUT/cfs_regs.sv\
      ../DUT/cfs_aligner_core.sv\
      ../DUT/cfs_aligner.sv

# Compile Subsystem
comp:
	vlog $(rtl) 
      
      	
